---
# https://golangci-lint.run/usage/configuration/
run:
  go: '1.18'
  timeout: 5m
linters:
  presets:
    - bugs
    - error
    - performance
    - sql
    - module
    - format
    - import
  enable:
    - predeclared
  disable:
    - maligned # deprecated by fieldalignment
    - scopelint # deprecated by exportloopref
    - gci # too strict
    - contextcheck # too restrictive
    - gomoddirectives # TODO remove after scany/tern v2 are released
    - musttag # cache uses JSON for models (Account)
linters-settings:
  govet:
    check-shadowing: true
  gosec:
    excludes:
      - G112 # slowloris attack - TODO (easyfix)
issues:
  exclude-rules:
    # Makes easier to write test code.
    - path: '(.+)_test\.go'
      linters:
        - forcetypeassert

    # Exclude generated files.
    - path: \.gen\.go
      linters:
        - typecheck
        - errcheck
