{
 "title": "Provisioning",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "5m,30m,1h,6h,12h,1d,3d,7d" },
   { "name": "type", "label": "Hyperscaler type", "query": "aws,azure,gcp" }
  ]
 },
 "panels": [
  { "title": "Job scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reservation process rate per hyperscaler (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(provisioning_reservations_24h_count{result=\"pending\",provider=~\"$type\"} or on() vector(0)) / sum(provisioning_reservations_24h_count{provider=~\"$type\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reservation success rate per hyperscaler (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(provisioning_reservations_24h_count{result=\"success\",provider=~\"$type\"} or on() vector(0)) / sum(provisioning_reservations_24h_count{provider=~\"$type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reservation process rate per hyperscaler (28d)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(provisioning_reservations_28d_count{result=\"pending\",provider=~\"$type\"} or on() vector(0)) / sum(provisioning_reservations_28d_count{provider=~\"$type\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reservation success rate per hyperscaler (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(provisioning_reservations_28d_count{result=\"success\",provider=~\"$type\"} or on() vector(0)) / sum(provisioning_reservations_28d_count{provider=~\"$type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total reservations per hyperscaler (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(provisioning_reservations_24h_count{provider=~\"$type\"}) OR on() vector(0)",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Reservations per hyperscaler (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(provisioning_reservations_24h_count{result=\"pending\", provider=~\"$type\"}) OR on() vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(provisioning_reservations_24h_count{result=\"success\", provider=~\"$type\"}) OR on() vector(0)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(provisioning_reservations_24h_count{result=\"failure\", provider=~\"$type\"}) OR on() vector(0)",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Reservations per hyperscaler (28d)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(provisioning_reservations_28d_count{result=\"pending\", provider=~\"$type\"}) OR on() vector(0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(provisioning_reservations_28d_count{result=\"success\", provider=~\"$type\"}) OR on() vector(0)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(provisioning_reservations_28d_count{result=\"failure\", provider=~\"$type\"}) OR on() vector(0)",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "DB stats duration",
   "type": "stat",
   "description": "Average time spent calculating reservation stats. This is done every 30 minutes.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(provisioning_db_stats_duration_sum[35m]))\n/\nsum(rate(provisioning_db_stats_duration_count[35m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reservation error rate per hyperscaler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(provisioning_reservation_count{result=\"failure\",type=~\"$type\"}[$__interval]))\n/\nsum(rate(provisioning_reservation_count{type=~\"$type\"}[$__interval]))) or on() vector(0)",
     "legendFormat": "{{type}} failure"
    }
   ]
  },
  {
   "title": "Job duration (p99)",
   "type": "timeseries",
   "description": "Duration of background job types",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(provisioning_background_job_duration_bucket{type=~\"launch_instances_aws\"}[$__interval])) by (le)) OR on() vector(0)",
     "legendFormat": "AWS"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(provisioning_background_job_duration_bucket{type=~\"launch_instances_azure\"}[$__interval])) by (le)) OR on() vector(0)",
     "legendFormat": "Azure"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(provisioning_background_job_duration_bucket{type=~\"launch_instances_gcp\"}[$__interval])) by (le)) OR on() vector(0)",
     "legendFormat": "GCP"
    }
   ]
  },
  {
   "title": "Job queue size",
   "type": "timeseries",
   "description": "Number of jobs in the Redis job queue waiting to be picked up",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(sum_over_time(provisioning_job_queue_size[$__interval]))",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "In-flight jobs",
   "type": "timeseries",
   "description": "Number of jobs being processed by our workers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(provisioning_job_queue_inflight[$__interval]))",
     "legendFormat": "jobs"
    }
   ]
  },
  { "title": "Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "description": "The request latency for http requests over the selected date range",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(provisioning_http_request_duration_ms_bucket[$__interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(provisioning_http_request_duration_ms_bucket[$__interval]))by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(provisioning_http_request_duration_ms_bucket[$__interval]))by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "HTTP Request Stability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total HTTP Success Rate ",
   "type": "stat",
   "description": "Our SLO target",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"provisioning\",status!=\"5xx\"}[$__range]))/sum(rate(api_3scale_gateway_api_status{exported_service=\"provisioning\"}[$__range]))"
    }
   ]
  },
  {
   "title": "HTTP Success Latency 750ms Target",
   "type": "stat",
   "description": "Our SLO target",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(provisioning_http_request_duration_ms_bucket{code=~\"2.*\", le=\"750\"}[$__range])) / sum(rate(provisioning_http_request_duration_ms_bucket{code=~\"2.*\", le=\"+Inf\"}[$__range]))"
    }
   ]
  },
  {
   "title": "HTTP requests ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(provisioning_http_request_total[$__range]))"
    }
   ]
  },
  {
   "title": "HTTP  Throughput Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(sum(rate(provisioning_http_request_total{code!~\"4.*\"}[$interval])) OR on() vector(0)) - (sum(rate(provisioning_http_request_total{code=~\"5.*\"}[$interval])) OR on() vector(0)) ",
     "legendFormat": "success"
    },
    {
     "expr": "(sum(rate(provisioning_http_request_total{code=~\"5.*\"}[$interval])) OR on() vector(0))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Source Availability Request Stability and Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Source Availability Delivery Rate",
   "type": "stat",
   "description": "Percentage of source availability checks processed and delivered back to sources.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(provisioning_source_availability_check_request_total[$__range]))+ sum(rate(provisioning_invalid_source_availability_check_request_total[$__range])))/sum(rate(provisioning_http_request_total{path=\"/api/provisioning/v1/availability_status/sources/\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Source Availability Throughput Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "(sum(rate(provisioning_source_availability_check_request_total{error=\"false\"}[$__interval])) OR on() vector(0))",
     "legendFormat": "success"
    },
    {
     "expr": "(sum(rate(provisioning_source_availability_check_request_total{error=\"true\"}[$__interval])) OR on() vector(0))",
     "legendFormat": "error"
    },
    {
     "expr": "(sum(rate(provisioning_source_availability_check_request_total[$__interval])) OR on() vector(0))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Source Availability Check Latency",
   "type": "timeseries",
   "description": "The latency (p99, p90, p50) for source checks.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(provisioning_source_availability_check_request_duration_ms_bucket[$__interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(provisioning_source_availability_check_request_duration_ms_bucket[$__interval]))by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(provisioning_source_availability_check_request_duration_ms_bucket[$__interval]))by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}