---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: provisioning-cleanup-resources
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: provisioning-cleanup-${IMAGE_TAG}-${UID}
    annotations:
      "ignore-check.kube-linter.io/no-liveness-probe": "probes not required on Job pods"
      "ignore-check.kube-linter.io/no-readiness-probe": "probes not required on Job pods"
  spec:
    backoffLimit: 0
    template:
      spec:
        imagePullSecrets:
        - name: quay-cloudservices-pull
        restartPolicy: Never
        containers:
        - name: provisioning-cleanup-${IMAGE_TAG}-${UID}
          image: quay.io/redhatqe/cloudwash
          imagePullPolicy: Always
          args:
          - swach -d azure --all # remove "-d (dry run)" after overall review.
          env:
          - name:  CLEANUP_PROVIDERS_AZURE_AUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: azure_client_id
                name: iqe-vault
                optional: true
          - name: CLEANUP_PROVIDERS_AZURE_AUTH_SECRET_ID
            valueFrom:
              secretKeyRef:
                key: azure_client_secret
                name: iqe-vault
                optional: true
          - name: CLEANUP_PROVIDERS_AZURE_AUTH_TENANT_ID
            valueFrom:
              secretKeyRef:
                key: azure_tenant_id
                name: iqe-vault
                optional: true
          - name: CLEANUP_PROVIDERS_AZURE_AUTH_SUBSCRIPTION_ID
            valueFrom:
              secretKeyRef:
                key: subscription_id
                name: iqe-vault
                optional: true
          - name: CLEANUP_PROVIDERS_AZURE_AUTH_RESOURCE_GROUPS
            valueFrom:
              secretKeyRef:
                key: resource_group
                name: iqe-vault
          - name: CLEANUP_PROVIDERS_AZURE_AUTH_REGIONS
            valueFrom:
              secretKeyRef:
                key: location
                name: iqe-vault
                optional: true
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: UID
  description: "Unique job name suffix"
  generate: expression
  from: "[a-z0-9]{6}"
