---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: provisioning-cleanup-resources
objects:
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: provisioning-cleanup
    annotations:
      "ignore-check.kube-linter.io/no-liveness-probe": "probes not required on Job pods"
      "ignore-check.kube-linter.io/no-readiness-probe": "probes not required on Job pods"
  spec:
    schedule: ${CRON_SCHEDULE}
    jobTemplate:
      spec:
        backoffLimit: 0
        template:
          spec:
            imagePullSecrets:
              - name: quay-cloudservices-pull
            restartPolicy: Never
            containers:
              - name: provisioning-cleanup
                image: quay.io/redhatqe/cloudwash
                imagePullPolicy: Always
                command:
                  - swach
                args:
                  - "azure"
                  - "--nics"
                  - "--vms"
                  - "--discs"
                volumeMounts:
                  - name: config-volume
                    mountPath: /opt/app-root/src/cloudwash/settings.yaml
                    subPath: settings.yaml
                env:
                  - name: CLEANUP_AZURE__AUTH__CLIENT_ID
                    valueFrom:
                      secretKeyRef:
                        key: azure_client_id
                        name: provisioning-azure-auth-secret
                  - name: CLEANUP_AZURE__AUTH__SECRET_ID
                    valueFrom:
                      secretKeyRef:
                        key: azure_client_secret
                        name: provisioning-azure-auth-secret
                  - name: CLEANUP_AZURE__AUTH__TENANT_ID
                    valueFrom:
                      secretKeyRef:
                        key: azure_tenant_id
                        name: provisioning-azure-auth-secret
                  - name: CLEANUP_AZURE__AUTH__SUBSCRIPTION_ID
                    valueFrom:
                      secretKeyRef:
                        key: subscription_id
                        name: provisioning-azure-auth-secret
            volumes:
              - name: config-volume
                configMap:
                  name: cloudwash-config
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
- name: UID
  description: "Unique job name suffix"
  generate: expression
  from: "[a-z0-9]{6}"
- name: CRON_SCHEDULE
  description: "Schedule for cron job"
  value: ''
  required: true
