---
apiVersion: v1
kind: Template
labels:
  app: provisioning-backend
  template: provisioning-backend
metadata:
  name: provisioning-backend
  annotations:
    description: API backend for provisioning in console.redhat.com

objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: provisioning-backend
      labels:
        app: provisioning-backend
        service: provisioning
    spec:
      envName: ${ENV_NAME}
      featureFlags: true
      testing:
        iqePlugin: provisioning
      deployments:
        - name: worker
          replicas: 2
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            command:
              - /pbworker
            initContainers:
              - name: run-migrations
                image: "${IMAGE}:${IMAGE_TAG}"
                command:
                  - /pbmigrate
                inheritEnv: true
            env:
              - name: LOGGING_LEVEL
                value: ${LOGGING_LEVEL}
              - name: DATABASE_LOGGING_LEVEL
                value: ${DATABASE_LOGGING_LEVEL}
              - name: TELEMETRY_ENABLED
                value: ${TELEMETRY_ENABLED}
              - name: TELEMETRY_LOGGER_ENABLED
                value: ${TELEMETRY_LOGGER_ENABLED}
              - name: CLOWDER_ENABLED
                value: ${CLOWDER_ENABLED}
              - name: REST_ENDPOINTS_IMAGE_BUILDER_URL
                value: "${IMAGEBUILDER_URL}/api/image-builder/v1"
              - name: AWS_KEY
                valueFrom:
                  secretKeyRef:
                    name: provisioning-aws-acc
                    key: aws_access_key_id
                    optional: false
              - name: AWS_SECRET
                valueFrom:
                  secretKeyRef:
                    name: provisioning-aws-acc
                    key: aws_secret_access_key
                    optional: false
              - name: AZURE_TENANT_ID
                value: ${AZURE_TENANT_ID}
              - name: AZURE_CLIENT_ID
                value: ${AZURE_CLIENT_ID}
              - name: AZURE_CLIENT_SECRET
                value: ${AZURE_CLIENT_SECRET}
              - name: APP_INSTANCE_PREFIX
                value: ${APP_INSTANCE_PREFIX}
              - name: APP_CACHE_TYPE
                value: ${APP_CACHE_TYPE}
              - name: WORKER_QUEUE
                value: ${WORKER_QUEUE}
              - name: SENTRY_ENABLED
                valueFrom:
                  secretKeyRef:
                    name: provisioning-sentry
                    key: enabled
                    optional: true
              - name: SENTRY_DSN
                valueFrom:
                  secretKeyRef:
                    name: provisioning-sentry
                    key: dsn
                    optional: true
            resources:
              limits:
                cpu: ${{CPU_LIMIT}}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: ${CPU_REQUESTS}
                memory: ${MEMORY_REQUESTS}
        - name: statuser
          # statuser pod must have exactly one replicas
          replicas: 1
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            command:
              - /pbstatuser
            initContainers:
              - name: run-migrations
                image: "${IMAGE}:${IMAGE_TAG}"
                command:
                  - /pbmigrate
                inheritEnv: true
            env:
              - name: LOGGING_LEVEL
                value: ${LOGGING_LEVEL}
              - name: DATABASE_LOGGING_LEVEL
                value: ${DATABASE_LOGGING_LEVEL}
              - name: TELEMETRY_ENABLED
                value: ${TELEMETRY_ENABLED}
              - name: TELEMETRY_LOGGER_ENABLED
                value: ${TELEMETRY_LOGGER_ENABLED}
              - name: CLOWDER_ENABLED
                value: ${CLOWDER_ENABLED}
              - name: REST_ENDPOINTS_IMAGE_BUILDER_URL
                value: "${IMAGEBUILDER_URL}/api/image-builder/v1"
              - name: AWS_KEY
                valueFrom:
                  secretKeyRef:
                    name: provisioning-aws-acc
                    key: aws_access_key_id
                    optional: false
              - name: AWS_SECRET
                valueFrom:
                  secretKeyRef:
                    name: provisioning-aws-acc
                    key: aws_secret_access_key
                    optional: false
              - name: SENTRY_ENABLED
                valueFrom:
                  secretKeyRef:
                    name: provisioning-sentry
                    key: enabled
                    optional: true
              - name: SENTRY_DSN
                valueFrom:
                  secretKeyRef:
                    name: provisioning-sentry
                    key: dsn
                    optional: true
              - name: APP_INSTANCE_PREFIX
                value: ${APP_INSTANCE_PREFIX}
              - name: APP_CACHE_TYPE
                value: ${APP_CACHE_TYPE}
            resources:
              limits:
                cpu: ${{CPU_LIMIT}}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: ${CPU_REQUESTS}
                memory: ${MEMORY_REQUESTS}
        - name: api
          replicas: 2
          webServices:
            public:
              enabled: true
              apiPath: provisioning
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            initContainers:
              - name: run-migrations
                image: "${IMAGE}:${IMAGE_TAG}"
                command:
                  - /pbmigrate
                inheritEnv: true
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /ping
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 35
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 120
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /ping
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 35
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 120
            env:
              - name: LOGGING_LEVEL
                value: ${LOGGING_LEVEL}
              - name: DATABASE_LOGGING_LEVEL
                value: ${DATABASE_LOGGING_LEVEL}
              - name: TELEMETRY_ENABLED
                value: ${TELEMETRY_ENABLED}
              - name: TELEMETRY_LOGGER_ENABLED
                value: ${TELEMETRY_LOGGER_ENABLED}
              - name: CLOWDER_ENABLED
                value: ${CLOWDER_ENABLED}
              - name: REST_ENDPOINTS_IMAGE_BUILDER_URL
                value: "${IMAGEBUILDER_URL}/api/image-builder/v1"
              - name: APP_COMPRESSION
                value: ${APP_COMPRESSION}
              - name: AWS_KEY
                valueFrom:
                  secretKeyRef:
                    name: provisioning-aws-acc
                    key: aws_access_key_id
                    optional: false
              - name: AWS_SECRET
                valueFrom:
                  secretKeyRef:
                    name: provisioning-aws-acc
                    key: aws_secret_access_key
                    optional: false
              - name: AZURE_TENANT_ID
                value: ${AZURE_TENANT_ID}
              - name: AZURE_CLIENT_ID
                value: ${AZURE_CLIENT_ID}
              - name: AZURE_CLIENT_SECRET
                value: ${AZURE_CLIENT_SECRET}
              - name: APP_INSTANCE_PREFIX
                value: ${APP_INSTANCE_PREFIX}
              - name: APP_CACHE_TYPE
                value: ${APP_CACHE_TYPE}
              - name: WORKER_QUEUE
                value: ${WORKER_QUEUE}
              - name: SENTRY_ENABLED
                valueFrom:
                  secretKeyRef:
                    name: provisioning-sentry
                    key: enabled
                    optional: true
              - name: SENTRY_DSN
                valueFrom:
                  secretKeyRef:
                    name: provisioning-sentry
                    key: dsn
                    optional: true
            resources:
              limits:
                cpu: ${{CPU_LIMIT}}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: ${CPU_REQUESTS}
                memory: ${MEMORY_REQUESTS}
      database:
        name: provisioning
        version: 13
      kafkaTopics:
        - topicName: platform.provisioning.internal.availability-check
          partitions: 1
          replicas: 3
        - topicName: platform.sources.event-stream
        - topicName: platform.sources.status
      inMemoryDb: true
      dependencies:
        - sources-api
      optionalDependencies:
        - image-builder

  - apiVersion: metrics.console.redhat.com/v1alpha1
    kind: FloorPlan
    metadata:
      name: provisioning-backend
      labels:
        app: provisioning-backend
        service: provisioning
    spec:
      database:
        secretName: ${FLOORIST_DB_SECRET_NAME}
      objectStore:
        secretName: ${FLOORIST_BUCKET_SECRET_NAME}
      logLevel: ${FLOORIST_LOGLEVEL}
      suspend: ${{FLOORIST_SUSPEND}}
      queries:
        - prefix: ${FLOORIST_QUERY_PREFIX}/reservations
          query: >-
            select r.created_at, r.finished_at, r.success,
                   a.account_number, a.org_id, d.source_id,
                   d.detail->'instance_type' as type,
                   d.detail->'region' as region,
                   d.detail->'amount' as amount
            from reservations r
            join aws_reservation_details d on r.id = d.reservation_id
            join accounts a on r.account_id = a.id
            where provider = provider_type_aws()
            order by r.created_at;

# possible application ENV variables are in config/api.env.example
parameters:
  - description: ClowdEnv Name
    name: ENV_NAME
    required: true
  - description: Cpu limit of service
    name: CPU_LIMIT
    value: "1"
  - description: Cpu request increment
    name: CPU_REQUESTS
    value: 100m
  - description: memory limit of service
    name: MEMORY_LIMIT
    value: 1Gi
  - description: memory request increment
    name: MEMORY_REQUESTS
    value: 100Mi
  - description: Image tag
    name: IMAGE_TAG
    required: true
  - description: Image name
    name: IMAGE
    value: quay.io/cloudservices/provisioning-backend
  - description: Logging level (trace, debug, info, warn, error, fatal, panic)
    name: LOGGING_LEVEL
    value: "debug"
  - description: Postgres driver logging level (trace, debug, info, warn, error, fatal, panic)
    name: DATABASE_LOGGING_LEVEL
    value: "debug"
  - description: OpenTelemetry collecting
    name: TELEMETRY_ENABLED
    value: "true"
  - description: OpenTelemetry export into the logger
    name: TELEMETRY_LOGGER_ENABLED
    value: "true"
  - description: Enable compression of the API responses
    name: APP_COMPRESSION
    value: "true"
  - description: Determines Clowder deployment
    name: CLOWDER_ENABLED
    value: "true"
  - name: FLOORIST_LOGLEVEL
    description: Floorist loglevel config
    value: 'INFO'
  - name: FLOORIST_SUSPEND
    description: Disable Floorist cronjob execution
    value: 'false'
  - name: FLOORIST_DB_SECRET_NAME
    description: Name of the secret for accessing the database for floorist
    value: "provisioning-db"
  - name: FLOORIST_BUCKET_SECRET_NAME
    description: Name of the secret for accessing the bucket for the floorist data dump
    value: "floorist-bucket"
  - name: FLOORIST_QUERY_PREFIX
    description: Prefix for separating query data between prod and stage in the bucket
    value: "hms_analytics/provisioning/unknown"
  - description: ImageBuilder service URL
    name: IMAGEBUILDER_URL
    required: false
    value: "http://image-builder:8080"
  - description: Instance prefix adds string to all instance names, leave blank for production
    name: APP_INSTANCE_PREFIX
    value: ""
  - description: Application cache type (none, memory or redis)
    name: APP_CACHE_TYPE
    value: "redis"
  - description: Internal queue type (memory/sqs/postgres).
    name: WORKER_QUEUE
    value: "redis"
  # TODO: remove this once we have secret
  - description: Azure tenant of the service account
    name: AZURE_TENANT_ID
    required: false
  - description: Azure tenant of the service account
    name: AZURE_CLIENT_ID
    required: false
  - description: Azure tenant of the service account
    name: AZURE_CLIENT_SECRET
    required: false
