---
apiVersion: v1
kind: Template
labels:
  app: provisioning-backend
  template: provisioning-backend
metadata:
  name: provisioning-backend
  annotations:
    description: API backend for provisioning in console.redhat.com

objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: provisioning-backend
      labels:
        app: provisioning-backend
        service: provisioning
    spec:
      envName: ${ENV_NAME}
      testing:
        iqePlugin: provisioning
      deployments:
        - name: service
          minReplicas: ${{MIN_REPLICAS}}
          webServices:
            public:
              enabled: true
              apiPath: provisioning
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            initContainers:
              - name: run-migrations
                image: "${IMAGE}:${IMAGE_TAG}"
                command:
                  - /pbmigrate
                inheritEnv: true
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /ping
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 35
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 120
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /ping
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 35
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 120
            env:
              - name: CLOWDER_ENABLED
                value: ${CLOWDER_ENABLED}
              - name: CLOUDWATCH_ENABLED
                value: ${CLOUDWATCH_ENABLED}
              - name: OPEN_API_FILEPATH
                value: ${OPEN_API_FILEPATH}
              - name: APP_COMPRESSION
                value: ${APP_COMPRESSION}
              - name: AWS_KEY
                valueFrom:
                  secretKeyRef:
                    name: provisioning-aws-acc
                    key: aws_access_key_id
                    optional: false
              - name: AWS_SECRET
                valueFrom:
                  secretKeyRef:
                    name: provisioning-aws-acc
                    key: aws_secret_access_key
                    optional: false
              - name: AWS_INSTANCE_PREFIX
                value: ${AWS_INSTANCE_PREFIX}
              - name: WORKER_QUEUE
                value: ${WORKER_QUEUE}
              - name: WORKER_CONCURRENCY
                value: ${WORKER_CONCURRENCY}
              - name: WORKER_HEARTBEAT_SEC
                value: ${WORKER_HEARTBEAT_SEC}
              - name: WORKER_MAX_BEATS
                value: ${WORKER_MAX_BEATS}
            resources:
              limits:
                cpu: ${{CPU_LIMIT}}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: ${CPU_REQUESTS}
                memory: ${MEMORY_REQUESTS}
      database:
        name: provisioning-backend
        version: 13
      dependencies:
        - sources-api

parameters:
  - description: ClowdEnv Name
    name: ENV_NAME
    required: true
  - description: Cpu limit of service
    name: CPU_LIMIT
    value: "1"
  - description: Cpu request increment
    name: CPU_REQUESTS
    value: 100m
  - description: memory limit of service
    name: MEMORY_LIMIT
    value: 1Gi
  - description: memory request increment
    name: MEMORY_REQUESTS
    value: 100Mi
  - name: MIN_REPLICAS
    value: "1"
  - description: Image tag
    name: IMAGE_TAG
    required: true
  - description: Image name
    name: IMAGE
    value: quay.io/cloudservices/provisioning-backend
  - description: Enable compression of the API responses
    name: APP_COMPRESSION
    value: "true"
  - description: Determines Clowder deployment
    name: CLOWDER_ENABLED
    value: "true"
  - description: AWS CloudWatch logging integration
    name: CLOUDWATCH_ENABLED
    value: "false"
  - description: AWS instance prefix adds string to all instance names, leave blank for production
    name: AWS_INSTANCE_PREFIX
    value: ""
  - description: Internal queue type (memory/sqs/postgres).
    name: WORKER_QUEUE
    value: "memory"
  - description: Internal queue concurrency, how many goroutines to run in parallel.
    name: WORKER_CONCURRENCY
    value: "100"
  - description: Internal queue heartbeat interval. How often to update job liveness information.
    name: WORKER_HEARTBEAT_SEC
    value: "30"
  - description: Internal queue beat threshold. Now many times the beat can be updated until job is cancelled.
    name: WORKER_MAX_BEATS
    value: "10"
  - name: OPEN_API_FILEPATH
    value: /var/tmp/openapi.json
