---
apiVersion: v1
kind: Template
labels:
  app: provisioning
  template: provisioning
metadata:
  name: provisioning
  annotations:
    description: API backend for provisioning in console.redhat.com

objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: provisioning
      labels:
        service: provisioning
    spec:
      envName: ${ENV_NAME}
      testing: 
        iqePlugin: hms-provisioning
      deployments:
        - name: service
          minReplicas: ${{MIN_REPLICAS}}
          webServices:
            public:
              enabled: true
              apiPath: provisioning
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            initContainers:
              - name: run-migrations
                image: "${IMAGE}:${IMAGE_TAG}"
                command:
                  - /pbmigrate
                inheritEnv: true
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /ping
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 35
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 120
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /ping
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 35
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 120
            env:
              - name: CLOWDER_ENABLED
                value: ${CLOWDER_ENABLED}
              - name: ENABLE_CLOUDWATCH_LOGGING
                value: ${ENABLE_CLOUDWATCH_LOGGING}
              - name: OPENAPIFILEPATH
                value: ${OPEN_API_FILEPATH}
            resources:
              limits:
                cpu: ${{CPU_LIMIT}}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: ${CPU_REQUESTS}
                memory: ${MEMORY_REQUESTS}
      database:
        name: provisioning-backend
        version: 13

parameters:
  - description: ClowdEnv Name
    name: ENV_NAME
    required: true
  - description: Cpu limit of service
    name: CPU_LIMIT
    value: "1"
  - description: memory limit of service
    name: MEMORY_LIMIT
    value: 1Gi
  - name: MIN_REPLICAS
    value: "1"
  - description: Image tag
    name: IMAGE_TAG
    required: true
  - description: Image name
    name: IMAGE
    value: quay.io/envision/provisioning-backend
  - description: Determines Clowder deployment
    name: CLOWDER_ENABLED
    value: "true"
  - description: Determines if Cloud Watch logging is enabled
    name: ENABLE_CLOUDWATCH_LOGGING
    value: "false"
  - name: OPEN_API_FILEPATH
    value: /var/tmp/openapi.json
