---
apiVersion: v1
kind: Template
metadata:
  name: provisioning-backend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: provisioning-backend
    spec:
      envName: ${ENV_NAME}
      deployments:
        - name: service
          minReplicas: ${{MIN_REPLICAS}}
          web: true
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            initContainers:
              - name: run-migrations
                command:
                  - bash
                  - -c
                  - pbmigrate
                inheritEnv: true
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 35
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 120
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8000
                scheme: HTTP
              initialDelaySeconds: 35
              periodSeconds: 5
              successThreshold: 1
              timeoutSeconds: 120
            env:
              - name: CLOWDER_ENABLED
                value: ${CLOWDER_ENABLED}
              - name: ENABLE_CLOUDWATCH_LOGGING
                value: ${ENABLE_CLOUDWATCH_LOGGING}
              - name: OPENAPIFILEPATH
                value: ${OPEN_API_FILEPATH}
            resources:
              limits:
                cpu: ${{CPU_LIMIT}}
                memory: ${MEMORY_LIMIT}
              requests:
                cpu: 500m
                memory: 512Mi
      database:
        name: provisioning-backend

parameters:
  - description: Cpu limit of service
    name: CPU_LIMIT
    value: "1"
  - description: memory limit of service
    name: MEMORY_LIMIT
    value: 1Gi
  - name: MIN_REPLICAS
    value: "1"
  - description: Image tag
    name: IMAGE_TAG
    required: true
  - description: Image name
    name: IMAGE
    value: quay.io/cloudservices/idp-configs-api
  - description: Determines Clowder deployment
    name: CLOWDER_ENABLED
    value: "true"
  - description: ClowdEnv Name
    name: ENV_NAME
    requred: false
  - description: Determines if Cloud Watch logging is enabled
    name: ENABLE_CLOUDWATCH_LOGGING
    value: "false"
  - name: OPEN_API_FILEPATH
    value: /var/tmp/openapi.json