{
 "title": "Provisioning",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "5m,30m,1h,6h,12h,1d,3d,7d" },
   { "name": "type", "label": "Hyperscaler type", "query": "aws,azure,gcp" }
  ]
 },
 "panels": [
  { "title": "Job scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reservation success rate per hyperscaler",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(provisioning_reservation_count{result=\"success\",type=~\"$type\"}[$__range]))\n/\nsum(increase(provisioning_reservation_count{type=~\"$type\"}[$__range]))) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total reservations per hyperscaler",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(provisioning_reservation_count{type=~\"$type\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reservation duration per hyperscaler (p95)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(provisioning_background_job_duration_bucket{type=~\"launch_instances_$type\"}[$__range])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reservation error rate per hyperscaler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(provisioning_reservation_count{result=\"failure\",type=~\"$type\"}[$__interval]))\n/\nsum(rate(provisioning_reservation_count{type=~\"$type\"}[$__interval]))) or on() vector(0)",
     "legendFormat": "{{type}} failure"
    }
   ]
  },
  {
   "title": "Job duration per hyperscaler",
   "type": "timeseries",
   "description": "Duration of background job types",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(provisioning_background_job_duration_bucket{type=~\"launch_instances_$type\"}[$__interval])) by (le)) OR on() vector(0)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(provisioning_background_job_duration_bucket{type=~\"launch_instances_$type\"}[$__interval])) by (le)) OR on() vector(0)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Job queue size",
   "type": "timeseries",
   "description": "Number of jobs in the Redis job queue waiting to be picked up",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(sum_over_time(provisioning_job_queue_size[$__interval]))",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "In-flight jobs",
   "type": "timeseries",
   "description": "Number of jobs being processed by our workers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(provisioning_job_queue_inflight[$__interval]))",
     "legendFormat": "jobs"
    }
   ]
  },
  { "title": "Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "description": "The request latency for http requests over the selected date range",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(provisioning_http_request_duration_ms_bucket[$__interval])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(provisioning_http_request_duration_ms_bucket[$__interval]))by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(provisioning_http_request_duration_ms_bucket[$__interval]))by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "HTTP Request Stability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total HTTP Success Rate ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(provisioning_http_request_total{code=~\"2.*\"}[$__range]))/sum(rate(provisioning_http_request_total[$__range]))"
    }
   ]
  },
  {
   "title": "HTTP requests ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(provisioning_http_request_total[$__range]))"
    }
   ]
  },
  {
   "title": "HTTP  Throughput Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(rate(provisioning_http_request_total{code!~\"4.*\"}[$interval])) OR on() vector(0)) - (sum(rate(provisioning_http_request_total{code=~\"5.*\"}[$interval])) OR on() vector(0)) ",
     "legendFormat": "success/sec"
    },
    {
     "expr": "(sum(rate(provisioning_http_request_total{code=~\"5.*\"}[$interval])) OR on() vector(0))",
     "legendFormat": "errors/sec"
    }
   ]
  },
  {
   "title": "HTTP  Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(provisioning_http_request_duration_ms_bucket{le=\"200\"}[$__range])) / sum(rate(provisioning_http_request_duration_ms_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source Availability Request Stability and Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Source Availability Success Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(provisioning_source_availability_check_request_total[$__range]))+ sum(rate(provisioning_invalid_source_availability_check_request_total[$__range])))/sum(rate(provisioning_http_request_total{path=\"/api/provisioning/v1/availability_status/sources/\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Source Availability Throughput Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(rate(provisioning_source_availability_check_request_total{error=\"false\"}[$__interval])) OR on() vector(0))",
     "legendFormat": "success/sec"
    },
    {
     "expr": "(sum(rate(provisioning_source_availability_check_request_total{error=\"true\"}[$__interval])) OR on() vector(0))",
     "legendFormat": "errors/sec"
    }
   ]
  },
  {
   "title": "Source Availability Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 1, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(provisioning_source_availability_check_request_duration_ms_bucket{le=\"5000\"}[$__range])) / sum(rate(provisioning_source_availability_check_request_duration_ms_count[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}