---
package: sources
generate:
  models: true
  client: true
output: ./internal/clients/http/sources/client.gen.go
output-options:
  include-tags:
    - sources
    - "application types"
    - "applications"
    - source types
  exclude-schemas:
    - BulkCreateResponse # generator issue: redeclaration
    - ID
