BEGIN;

CREATE TABLE accounts
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_number TEXT UNIQUE CHECK (NOT empty(account_number)),
  org_id TEXT NOT NULL UNIQUE CHECK (NOT empty(org_id))
);

COMMIT;
