CREATE TABLE sources
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES accounts(id),
    name TEXT CHECK (NOT empty(name)),
    provider INTEGER NOT NULL CHECK (valid_provider(provider)),
    auth_id TEXT NOT NULL CHECK (NOT empty(auth_id)),
    source_id BIGINT NOT NULL UNIQUE CHECK (NOT empty(source_id)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
