CREATE TABLE reservations
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider INTEGER NOT NULL CHECK (valid_provider(provider)),
  account_id BIGINT NOT NULL REFERENCES accounts(id),
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
  status TEXT NOT NULL CHECK (NOT empty(status)),
  finished_at TIMESTAMP,
  success BOOLEAN,

  UNIQUE (id, provider)
);

CREATE TABLE instance_reservation
(
  reservation_id BIGINT NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
  instance_id TEXT NOT NULL UNIQUE
);

CREATE TABLE aws_reservation_details
(
  reservation_id BIGINT NOT NULL,
  provider INTEGER NOT NULL DEFAULT provider_type_aws(),
  pubkey_id BIGINT REFERENCES pubkeys(id),
  source_id INTEGER NOT NULL,
  instance_type TEXT NOT NULL,
  amount INTEGER NOT NULL,
  ami TEXT NOT NULL,
  aws_reservation_id TEXT,

  FOREIGN KEY (reservation_id, provider) REFERENCES reservations(id, provider) ON DELETE CASCADE,
  CHECK (provider = provider_type_aws())
);
