CREATE TABLE reservations
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL REFERENCES accounts(id),
  pubkey_id BIGINT NOT NULL REFERENCES accounts(id),
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
  status TEXT NOT NULL CHECK (NOT empty(status)),
  finished_at TIMESTAMP,
  success BOOLEAN
);
