CREATE TABLE reservations
(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider INTEGER NOT NULL CHECK (valid_provider(provider)),
  account_id BIGINT NOT NULL REFERENCES accounts(id),
  created_at TIMESTAMP NOT NULL DEFAULT current_timestamp,
  status TEXT NOT NULL CHECK (NOT empty(status)),
  finished_at TIMESTAMP,
  success BOOLEAN,

  UNIQUE (id, provider)
);

CREATE TABLE aws_reservation_details
(
  reservation_id BIGINT NOT NULL,
  provider INTEGER NOT NULL DEFAULT provider_type_aws(),
  pubkey_id BIGINT REFERENCES pubkeys(id),

  FOREIGN KEY (reservation_id, provider) REFERENCES reservations(id, provider) ON DELETE CASCADE,
  CHECK (provider = provider_type_aws())
);
