style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/RHEnVision/provisioning-backend
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - refactor
        - perf
        - chore
        - demo
        - docs
        - style
        - test
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      refactor: Refactoring
      perf: Performance
      chore: Chores
      demo: Demo
      docs: Documentation
      style: Code Style
      test: Testing
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - #
  notes:
    keywords:
      - BREAKING CHANGE
