# Example configuration, copy file as "local.yaml" and edit as needed.

# PostgreSQL
# database:
#   host: localhost
#   port: 5432
#   name:
#   user:
#   password:
#   maxOpenConn: 25
#   maxIdleConn: 20
#   maxLifetime: 5m
#   maxIdletime: 10m
#   # 1-none, 2-error, 3-warn, 4-info, 5-debug, 6-trace
#   loglevel: 1

# logging:
#   # Overall log level (-1 trace, 0 debug, 1 info ... 5 panic)
#   level: 1
#   # Write logs to standard output in human-readable form
#   stdout: false

# AWS provisioning account (EC2, STS...)
# aws:
#   region: us-east-1
#   key:
#   secret:
#   session:

# AWS CloudWatch logger
# cloudwatch:
#   enabled: false
#   region: us-east-1
#   key:
#   secret:
#   session:
#   group: group
#   stream: stream

# restEndpoints:
#   imageBuilder:
#     url:
#   sources:
#     url:

# featureFlags:
#   # development or production
#   environment: development
#   # When panic error is not rescued, exit the application instead of returning 500.
#   exitOnPanic: false

# worker:
#   # memory, sqs or postrges
#   queue: postgres
#   # amount of goroutines for processing (CPU cores or more)
#   concurrency: 50
#   # heartbeat update rate (seconds)
#   hearbeatSec: 30
#   # maximum amount of heartbeat updates
#   maxBeats: 10

#   # how many goroutines to spawn per a worker process (typically hundreds)
#   concurrency: 8
#   # run workers as part of API backend (not for production)
#   inprocess: false
