# Example configuration, copy file as "local.yaml" and edit as needed.

# PostgreSQL
# database:
#   host: localhost
#   port: 5432
#   name:
#   user:
#   password:
#   maxOpenConn: 25
#   maxIdleConn: 20
#   maxLifetime: 5m
#   maxIdletime: 10m
#   # 1-none, 2-error, 3-warn, 4-info, 5-debug, 6-trace
#   loglevel: 1

# logging:
#   # Overall log level (-1 trace, 0 debug, 1 info ... 5 panic)
#   level: 1
#   # Write logs to standard output in human-readable form
#   stdout: false

# AWS CloudWatch logger
# cloudwatch:
#   enabled: false
#   group: group
#   stream: stream

# featureFlags:
#   # development or production
#   environment: development
#   # When panic error is not rescued, exit the application instead of returning 500.
#   exitOnPanic: false
