# Example configuration, copy file as "local.yaml" and edit as needed.

# Postgres
database:
  host: localhost
  port: 5432
  name:
  user:
  password:
  #minConn: 2
  #maxConn: 100
  #maxLifetime: 2h
  #maxIdleTime: 15m
  # Database tracing level, not effective if telemetry is enabled. Possible values:
  # none, error, warn, info, debug, trace
  #loglevel: trace

logging:
  # Overall log level (-1 trace, 0 debug, 1 info ... 5 panic)
  level: 1
  # Write logs to standard output in human-readable form
  stdout: false
  # Truncate log fields to specific size, only useful for development to keep
  # the standard output clean and human-readable. Set to zero or comment out
  # to disable.
  maxField: 0

telemetry:
  # OpenTelemetry tracing support
  #enabled: true
  # Jaeger Tracing exporter
  jaeger:
    #enabled: true
    #endpoint: http://localhost:14268/api/traces
  # Send OpenTelemetry output to logger as trace log level. No other exporting
  # is currently supported, Jaeger exporting is planned for the platform.
  logger:
    #enabled: true

app:
  # HTTP transparent gzip compression
  compression: false
  # Application-level clache
  cache:
    # Item expiration time (1 hour)
    #expiration:
    # Cleanup interval (5 minutes)
    #cleanupInterval:
    # Individual application cache features
    typeAppId: true
    account: true
  # Instance name prefix for all providers (useful only for testing)
  instancePrefix:

# AWS service account credentials
aws:
  key:
  secret:
  session:
  # detailed logging including headers and body into trace log level (verbose!)
  logging: false
  # default region for non-regional requests (when region is not provided by the user)
  defaultRegion: us-east-1

# Azure service account credentials
azure:
  # Tenant or Organization ID
  tenantId: 00000000-0000-0000-0000-000000000000
  # Subscription ID
  subscriptionId: 00000000-0000-0000-0000-000000000000
  # Application (Client) ID
  clientId: 00000000-0000-0000-0000-000000000000
  # Secret value
  clientSecret:
  # default region for non-regional requests
  defaultRegion: eastus

# GCP service account credentials
gcp:
  # Base64-encoded credentials JSON file (defaults to empty JSON)
  json:
  # default region for non-regional requests
  defaultZone: us-east1-b

# AWS CloudWatch logger
cloudwatch:
  enabled: false
  region: us-east-1
  key:
  secret:
  session:
  group: group
  stream: stream

restEndpoints:
  # complete request and response logging (do not use in production)
  traceData: false
  imageBuilder:
    url: https://xxx.stage.redhat.com/api/image-builder/v1
    # basic auth and proxy is only useful for development against stage
    username: stage-account
    password: only_for_development
    proxy:
      url: http://squid.xxx.redhat.com:3128
  sources:
    url: https://xxx.stage.redhat.com/api/sources/v3.1
    # basic auth and proxy is only useful for development against stage
    username: stage-account
    password: only_for_development
    proxy:
      url: http://squid.xxx.redhat.com:3128

featureFlags:
  # development or production
  environment: development
  # When panic error is not rescued, exit the application instead of returning 500.
  exitOnPanic: false

worker:
  # memory, sqs or postrges
  queue: postgres
  # amount of goroutines for processing (CPU cores or more)
  concurrency: 50
  # heartbeat update rate (seconds)
  heartbeatSec: 30
  # maximum amount of heartbeat updates
  maxBeats: 10
  # run workers as part of API backend (not for production)
  inprocess: false
