---
package: sources
generate:
  models: true
  client: true
output: ./internal/clients/sources/client.gen.go
compatibility:
  old-enum-conflicts: true # generator issue: redeclaration of EndpointAvailabilityStatus
output-options:
  include-tags:
    - sources
    - "application types"
  exclude-schemas:
    - BulkCreateResponse # generator issue: redeclaration
