// @no-log
POST http://{{hostname}}:{{port}}/{{prefix}}/pubkeys/ HTTP/1.1
Content-Type: application/json
X-Rh-Identity: {{identity}}

{
  "account_id": 1,
  "name": "random-key-{{$randomInt}}",
  "body": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvquRAb8jVK8k7im+Rsie768LEHgd3BmSureOpjVpgc/EjtZPR2kmt5wVkgufBqsOO9zftUbbN+THhxMi1EKnIqNkTypiaSFqKuKKx/G4Qp4NhYaXBMomlMdSJggM+/Uuves2LWgq+B58X3z0qhRaGMK1S3Dze7jkY/OkYLPHUguLniJ1SZY4xrCeemUUO+TEZisLoE1AH/51cwaOxfFqkM8k+OSPveJ2LDYROgdSMssnKWh0z9yfR9FgUn7d0Jiyjm4d3D4QdLT3TRF3uxTlQ0BBFEq3B94RrP0c/cz9j0oduKNovigDYxkZWudCdg/gg8plK6YXavdzhcHsnB7K3 {{$randomInt}}"
}
