// @no-log
POST http://{{hostname}}:{{port}}/{{prefix}}/pubkeys/ HTTP/1.1
Content-Type: application/json
X-Rh-Identity: {{identity}}

{
  "name": "this will fail because account id is missing and body is empty",
  "body": ""
}
