// @no-log
POST http://{{hostname}}:{{port}}/{{prefix}}/reservations/aws HTTP/1.1
Content-Type: application/json
X-Rh-Identity: {{identity}}

{

  "source_id": 1,
  "ami": "ami-0cff7528ff583bf9a",
  "amount": 1,
  "instance_type": "t1.micro",
  "pubkey_id": 1
}
