// @no-log
POST http://{{hostname}}:{{port}}/{{prefix}}/reservations/aws HTTP/1.1
Content-Type: application/json
X-Rh-Identity: {{identity}}

{

  "source_id": 1,
  "image_id": "2bc640f6-927a-404a-9594-5b2da7e06608",
  "amount": 1,
  "instance_type": "t1.micro",
  "pubkey_id": 1
}
