// @no-log
POST http://{{hostname}}:{{port}}/{{prefix}}/reservations/azure HTTP/1.1
Content-Type: application/json
X-Rh-Identity: {{identity}}

{
  "name": "azure-linux-us-east",
  "location": "eastus_1",
  "source_id": "{{source_id_azure}}",
  "image_id": "composer-api-e7e1c242-4ce8-4d5e-a5d0-75720e91afca",
  "amount": 1,
  "instance_size": "Standard_B1ls",
  "pubkey_id": 2,
  "poweroff": true,
  "resource_group": "{{azure-resource-group}}"
}
