// @no-log
POST http://{{hostname}}:{{port}}/{{prefix}}/reservations/aws HTTP/1.1
Content-Type: application/json
X-Rh-Identity: {{identity}}

{
  "name": "amz-linux-us-east-1",
  "source_id": "1",
  "image_id": "ami-05fa00d4c63e32376",
  "amount": 1,
  "instance_type": "t1.micro",
  "pubkey_id": 1,
  "poweroff": true
}
