// @no-log
POST http://{{hostname}}:{{port}}/{{prefix}}/reservations/azure HTTP/1.1
Content-Type: application/json
X-Rh-Identity: {{identity}}

{
  "name": "azure-linux-us-east",
  "source_id": "{{azure-source-id}}",
  "image_id": "composer-api-92ea98f8-7697-472e-80b1-7454fa0e7fa7",
  "amount": 2,
  "instance_size": "Standard_B1ls",
  "pubkey_id": {{pubkey_id}},
  "poweroff": true
}
