---
openapi: 3.0.0
info:
  license:
    name: GPL-3.0
  title: provisioning-api
  version: 0.0.2

paths:
  /pubkeys/{ID}:
    get:
      operationId: getPubkeyByID
      description: 'Returns a particular resource.'
      parameters:
        - name: ID
          in: path
          required: true
          description: 'Database ID of resource.'
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: 'Returned on success.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Pubkey'
        "404":
            $ref: "#/components/responses/NotFound"
        "500":
            $ref: '#/components/responses/InternalError'
  /pubkeys:
    get:
      operationId: getPubkeyList
      description: 'Returns list of resources.'
      responses:
        '200':
          description: 'Returned on success.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/v1.Pubkey'
        "500":
            $ref: '#/components/responses/InternalError'
