---
openapi: 3.0.0
info:
  description: "THIS API IS IN DEVELOPMENT - ENDPOINTS MIGHT CHANGE"
  license:
    name: GPL-3.0
  title: provisioning-api
  version: 1.0.0

paths:
  /pubkeys/{ID}:
    get:
      operationId: getPubkeyByID
      description: 'Returns a particular resource.'
      parameters:
        - name: ID
          in: path
          required: true
          description: 'Database ID of resource.'
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: 'Returned on success.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Pubkey'
        "404":
            $ref: "#/components/responses/NotFound"
        "500":
            $ref: '#/components/responses/InternalError'
  /pubkeys:
    get:
      operationId: getPubkeyList
      description: 'Returns list of resources.'
      responses:
        '200':
          description: 'Returned on success.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/v1.Pubkey'
        "500":
          $ref: '#/components/responses/InternalError'
  /sources:
    get:
      description: 'Return list of provisioning sources'
      operationId: getListSources
      responses:
        '200':
          description: Returned on success.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/v1.Source'
        '500':
          $ref: "#/components/responses/InternalError"
  /sources/{ID}:
    get:
      description: 'Return a provisioning source by id'
      operationId: getSourceID
      parameters:
        - name: ID
          in: path
          required: true
          description: 'Source ID from Sources Database.'
          schema:
            type: integer
            format: int64  
      responses:
        '200':
          description: Return on success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Source'
        '404':
          $ref: "#/components/responses/NotFound"
        '500':
          $ref: "#/components/responses/InternalError"
  /instance_types/{source_id}:
      get:
        description: 'Return a list of instance types'
        operationId: getListInstanceTypes
        parameters:
          - name: source_id
            in: path
            required: true
            description: 'Source ID from Sources Database.'
            schema:
              type: integer
              format: int64
        responses:
          '200':
            description: Return on success.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/v1.InstanceType'
          '404':
            $ref: "#/components/responses/NotFound"
          '500':
            $ref: "#/components/responses/InternalError"
