---
openapi: 3.0.0
info:
  license:
    name: GPL-3.0
  title: provisioning-api
  version: 0.0.2

paths:
  /pubkeys/{ID}:
    get:
      operationId: getPubkeyByID
      description: 'Returns a particular resource.'
      parameters:
        - name: ID
          in: path
          required: true
          description: 'Database ID of resource.'
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: 'Returned on success.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1.Pubkey'
        "404":
            $ref: "#/components/responses/NotFound"
        "500":
            $ref: '#/components/responses/InternalError'
  /pubkeys:
    get:
      operationId: getPubkeyList
      description: 'Returns list of resources.'
      responses:
        '200':
          description: 'Returned on success.'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/v1.Pubkey'
        "500":
            $ref: '#/components/responses/InternalError'
components:
  responses:
    BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/v1.ResponseError'
      description: The request's parameters are not sufficient
    InternalError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/v1.ResponseError'
      description: The server encountered with an internal error
    NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/v1.ResponseError'
      description: The specified resource was not found
  schemas:
    v1.Account:
      properties:
        account_number:
          type: string
        id:
          format: int64
          type: integer
        org_id:
          type: string
      type: object
    v1.Pubkey:
      properties:
        account_id:
          format: int64
          type: integer
        body:
          type: string
        id:
          format: int64
          type: integer
        name:
          type: string
      type: object
    v1.ResponseError:
      properties:
        msg:
          type: string
        request_id:
          type: string
      type: object
servers:
- description: Local development
  url: http://0.0.0.0:{port}/api/{applicationName}
  variables:
    applicationName:
      default: provisioning
    port:
      default: "8000"
